### ISSUE TITLE
About name garbled problem

### ISSUE THREAD

**Issue by langfengwangluo** [Sples1/ENT_FirstJoin#1]
If the user has a Chinese ID, the name in the database will become garbled.
![](http://p2.so.qhmsg.com/t02da5eb8d14c229a25.jpg)

**Comment by Sples1** [comment]
Hey!
Did you try to change your Database's character coding?

**Comment by Sples1** [comment]
Close due to inactivity and no informations about the problem. Also the problem can be solved with encoding change.
